# .github/workflows/deploy.yml

name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace API Key and Client ID
        run: |
          sed -i "s|%%GOOGLE_API_KEY%%|${{ secrets.GOOGLE_API_KEY }}|g" script.js
          sed -i "s|%%GOOGLE_CLIENT_ID%%|${{ secrets.GOOGLE_CLIENT_ID }}|g" script.js
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          cname: billdevsprint.com # <-- THÊM DÒNG NÀY
          commit_message: 'Deploy: ${{ github.event.head_commit.message }}'